[kubernetes]
symbol = "⛵ "
disabled = false
style = "dimmed blue"
[kubernetes.context_aliases]
"gke_nexttv-development-environment_europe-west1_primary" = "dev-primary"
"gke_nexttv-staging-environment_europe-west1_primary" = "staging-primary"
"gke_next-staging_europe-west1_testing" = "testing"

[line_break]
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
